CONTENT = {
    "tokens": {
        "mental": "Text becomes a sequence of **integer token IDs** from a fixed vocabulary—never raw Unicode in the transformer.",
        "why": "Billing, context limits, and latency are all counted in tokens; '2000 words' is meaningless to the API.",
        "concepts": ["Subword BPE/SentencePiece", "Vocab size trade-off", "Special tokens (BOS/EOS)", "Chars ≠ tokens", "Prompt + completion token budgets"],
        "how": "Tokenizer.encode(text) → list[int] → embedding lookup per ID.",
        "example": "Same sentence in English vs code may differ 2× in token count.",
        "bridge": "Like serializing structs—schema (vocab) must match consumer (model).",
        "production": ["Pre-count tokens before send", "Tokenizer version in model card", "Alert on context overflow"],
        "pitfalls": ["Assuming word count", "Mixing tokenizers across models"],
        "interview": ["What is a token?", "Why does code cost more tokens?"],
        "practice": "Tokenize 20 prompts; plot length distribution.",
    },
    "tokenization": {
        "mental": "Tokenization is a **compression codec** for text—splitting into reusable pieces.",
        "why": "Different tokenizers change cost, context fit, and multilingual behavior.",
        "concepts": ["BPE merge rules", "Normalization (NFKC)", "Unknown handling via subwords", "Decoder symmetry", "Hugging Face AutoTokenizer"],
        "how": "Train or download merges; encode/decode round-trip should recover text (mostly).",
        "example": "Medical terms split oddly → retrieval misses exact string match—hybrid search helps.",
        "bridge": "Version tokenizer with model in registry.",
        "production": ["Store tokenizer artifact with model version", "Test round-trip on corpus"],
        "pitfalls": ["Whitespace sensitivity", "Emoji edge cases"],
        "interview": ["BPE intuition?"],
        "practice": "Compare token counts for two tokenizer families on your docs.",
    },
    "embeddings": {
        "mental": "An embedding is a **dense vector** representing meaning—similar texts map nearby.",
        "why": "Powers semantic search, clustering, and as input to the first layer of many models.",
        "concepts": ["Contrastive training", "Pooling (mean/CLS/last)", "Normalization for cosine", "Embedding model vs LLM", "Dimension vs quality"],
        "how": "Text → encoder forward pass → vector in R^d.",
        "example": "FAQ question matches paraphrase in vector DB.",
        "bridge": "Like feature vectors in ML—except learned, not hand-crafted.",
        "production": ["Pick model for domain", "Batch embed offline", "Cache doc embeddings"],
        "pitfalls": ["Wrong model for legal/medical", "Not updating index on model change"],
        "interview": ["Embedding vs one-hot?"],
        "practice": "Embed 100 sentences; inspect nearest neighbors.",
    },
    "transformers": {
        "mental": "Repeated **blocks**: attention mixes tokens; FFN transforms each position; residuals + norm stabilize depth.",
        "why": "Dominant architecture for LLMs; you debug serving and context behavior at this abstraction.",
        "concepts": ["Decoder-only (GPT)", "Encoder-only (BERT)", "Encoder-decoder (T5)", "LM head", "Parameter count vs depth/width"],
        "how": "Embed + positions → L blocks → logits over vocab.",
        "example": "Chat model is decoder-only autoregressive stack.",
        "bridge": "Stack of layers ≈ pipeline stages—profile which stage dominates latency.",
        "production": ["Model card: layers, heads, hidden", "Max sequence length config"],
        "pitfalls": ["Using encoder model for open-ended chat", "Tokenizer mismatch"],
        "interview": ["Decoder vs encoder?", "What is a block?"],
        "practice": "Load config from HF; print architecture summary.",
    },
    "attention": {
        "mental": "Each token asks all positions: **how much should I listen?** Softmax weights pick a blend of values.",
        "why": "Core mechanism for contextual meaning and long-range dependencies.",
        "concepts": ["Q, K, V projections", "Scaled dot-product", "Multi-head", "Causal mask in decoders", "O(n²) memory naive"],
        "how": "Scores = QK^T/√d; mask; softmax; multiply V.",
        "example": "Pronoun resolves to noun earlier in sentence via attention weights.",
        "bridge": "Attention map is not logged in prod—debug with shorter prompts and ablations.",
        "production": ["FlashAttention for speed", "Context length caps"],
        "pitfalls": ["Lost-in-the-middle on long prompts", "Confusing self- vs cross-attention"],
        "interview": ["Attention formula?", "Why √d_k?"],
        "practice": "Toy 4-token masked attention in NumPy.",
        "code": "```python\n# scores[i,j] = dot(q_i, k_j) / sqrt(d); mask future; softmax row-wise\n```",
    },
    "positional-encoding": {
        "mental": "Attention is permutation-invariant without **position signal**—models need to know word order.",
        "why": "Order matters ('dog bites man'); RoPE/ALiBi extend length extrapolation.",
        "concepts": ["Sinusoidal PE (original)", "Learned positions", "RoPE (rotary)", "ALiBi slopes", "Relative position biases"],
        "how": "Add or rotate embeddings with position-dependent transform before attention.",
        "example": "RoPE common in Llama-class models for long context claims.",
        "bridge": "Like sequence numbers in event logs—order carries semantics.",
        "production": ["Respect max_position_embeddings", "Don't exceed trained length without testing"],
        "pitfalls": ["Extrapolating far beyond trained length"],
        "interview": ["Why positions needed?"],
        "practice": "Read model card for position scheme used.",
    },
    "pretraining": {
        "mental": "Train on **massive text** to predict next token—builds general language manifold.",
        "why": "Foundation of capabilities; you rarely pretrain from scratch in product teams.",
        "concepts": ["Causal LM objective", "Data cleaning at scale", "Compute budget (GPU-years)", "Emergent abilities with scale", "Checkpoints"],
        "how": "Shuffle tokens → batches → forward/backward → periodic eval on held-out perplexity/tasks.",
        "example": "GPT-style pretrain on web + books (filtered).",
        "bridge": "You consume checkpoints; focus on eval + alignment stage awareness.",
        "production": ["License of base model", "Provenance documentation"],
        "pitfalls": ["Training on leaked PII", "Undocumented data mix"],
        "interview": ["Objective of pretraining?"],
        "practice": "List risks of training on customer data without legal review.",
    },
    "instruction-tuning": {
        "mental": "Fine-tune on **(instruction, response)** pairs so the model follows user intent in chat format.",
        "why": "Raw pretrained models are not helpful assistants until SFT.",
        "concepts": ["SFT datasets (Alpaca-style)", "Chat templates", "Multi-turn formatting", "Quality filtering", "Overfitting to style"],
        "how": "Supervised loss on assistant tokens only (mask user tokens in some setups).",
        "example": "After SFT, model follows 'Summarize in bullets'.",
        "bridge": "Like API versioning—template strings must match training format at inference.",
        "production": ["Apply chat template in serving", "Version SFT data"],
        "pitfalls": ["Template mismatch → gibberish", "Tiny SFT destroying capabilities"],
        "interview": ["SFT vs pretrain?"],
        "practice": "Inspect `tokenizer.apply_chat_template` output.",
    },
    "alignment": {
        "mental": "Shape **behavior** toward human preferences and policies—beyond naive next-token prediction.",
        "why": "Safety, helpfulness, and brand tone for production assistants.",
        "concepts": ["RLHF pipeline", "Reward model", "PPO/DPO variants", "Constitutional rules", "Refusal behaviors"],
        "how": "SFT → (optional) reward model training → policy optimization or preference loss.",
        "example": "Model refuses harmful requests while staying helpful on benign tasks.",
        "bridge": "Policy layer in gateway complements model alignment—not a substitute.",
        "production": ["Red-team eval sets", "Monitor refusal rates", "Human review for edge cases"],
        "pitfalls": ["Over-refusal hurting UX", "Alignment tax on reasoning"],
        "interview": ["RLHF at high level?"],
        "practice": "Define 10 policy rules; test model compliance.",
    },
    "inference": {
        "mental": "**Frozen weights**, forward-only: prefill prompt, then decode tokens one by one.",
        "why": "What you ship in APIs and vLLM—distinct from training loops.",
        "concepts": ["Prefill vs decode", "KV cache", "Sampling", "Batching", "TTFT vs TPOT"],
        "how": "Load weights to GPU → run graph → stream tokens.",
        "example": "200ms TTFT, 40ms/token decode for a chat UI.",
        "bridge": "Size pods for concurrent sequences × context, not just QPS.",
        "production": ["max_tokens limits", "Concurrency caps", "Warm pools"],
        "pitfalls": ["OOM on long context", "Cold start loading 70B"],
        "interview": ["Prefill vs decode?"],
        "practice": "Measure TTFT and tokens/sec for one model endpoint.",
    },
    "context-window": {
        "mental": "A **fixed-size attention budget** for prompt + completion; overflow = truncate or error.",
        "why": "Architecture and memory hard limits; product must handle gracefully.",
        "concepts": ["n_ctx in config", "Truncation strategies", "Summarization middleware", "Lost-in-the-middle", "RAG to shrink prompt"],
        "how": "Count tokens; if over limit, drop oldest turns or compress retrieved chunks.",
        "example": "Chat history summarizer after 8k tokens.",
        "bridge": "Like max gRPC message size—design client behavior.",
        "production": ["Server-side token counter", "User-visible warnings"],
        "pitfalls": ["Silent truncation of system prompt", "Stuffing irrelevant RAG"],
        "interview": ["How handle long meetings?"],
        "practice": "Design truncation policy for multi-turn support bot.",
    },
    "temperature-sampling": {
        "mental": "Temperature **flattens or sharpens** the next-token distribution—creativity vs determinism.",
        "why": "Same prompt must not always mean same output in creative tasks; ops wants reproducibility elsewhere.",
        "concepts": ["T=0 greedy/near-deterministic", "top-k / top-p nucleus", "Seed (provider-dependent)", "Logits processing", "Temperature per task type"],
        "how": "logits /= T → softmax → sample or argmax.",
        "example": "Support bot T=0.2; brainstorming T=0.8.",
        "bridge": "Feature flag sampling params per use case.",
        "production": ["Log sampling config", "Eval at fixed T for regression"],
        "pitfalls": ["High T in extraction tasks", "Assuming seed portability across providers"],
        "interview": ["Temperature effect?"],
        "practice": "Run same prompt 20× at T=0 vs T=1; compare variance.",
    },
    "structured-output": {
        "mental": "Force model output to match **JSON/schema**—contracts for downstream code.",
        "why": "Agents and integrations need parseable data, not prose.",
        "concepts": ["JSON mode", "Grammar/constrained decoding", "Pydantic validation", "Repair retries", "Schema in prompt vs runtime"],
        "how": "Provide schema → generate → validate → retry with error hint.",
        "example": "Extract `{title, severity, owner}` from incident text.",
        "bridge": "Like protobuf validation in Go handlers.",
        "production": ["Max repair attempts", "Metrics on validation failure"],
        "pitfalls": ["Schema too large for context", "Trusting without validate"],
        "interview": ["Structured output strategies?"],
        "practice": "FastAPI endpoint returning Pydantic model from LLM JSON.",
    },
    "function-calling": {
        "mental": "Model emits **tool name + arguments**; runtime executes and feeds results back.",
        "why": "Ground actions in APIs, DBs, and systems—not hallucinated function results.",
        "concepts": ["OpenAI tools schema", "Parallel tool calls", "Tool choice auto/none/required", "Observation messages", "Idempotent tools"],
        "how": "Loop: completion with tool_calls → execute → append tool role message → continue.",
        "example": "get_weather(city) → API → model summarizes forecast.",
        "bridge": "Same as gRPC method dispatch with JSON args—add authz.",
        "production": ["Allowlist tools", "Timeouts", "Audit log"],
        "pitfalls": ["Executing without validation", "Prompt injection via tool output"],
        "interview": ["Tool loop steps?"],
        "practice": "Implement two tools with Pydantic arg validation.",
    },
    "model-selection": {
        "mental": "Pick **capability vs cost vs latency vs compliance**—not 'always biggest'.",
        "why": "Architecture and unit economics depend on model tier routing.",
        "concepts": ["Frontier vs small models", "Context length needs", "Multimodal", "Data residency", "Open vs closed weights"],
        "how": "Benchmark on your eval set; measure P95 latency and $/successful task.",
        "example": "Route tier-1 support to small model; escalate hard cases to large.",
        "bridge": "Model router in gateway—your Go comfort zone.",
        "production": ["Fallback model", "Version pinning", "Per-tenant policy"],
        "pitfalls": ["Benchmark on MMLU only", "Ignoring tokenizer/context limits"],
        "interview": ["How choose model for RAG?"],
        "practice": "Scorecard table for 3 models on 50 prompts.",
    },
}
