CONTENT = {
    "python-for-go-engineers": {
        "mental": "Python is the **AI ecosystem's glue language**—FastAPI services, eval scripts, notebooks—not a replacement for your Go control plane.",
        "why": "Hugging Face, PyTorch, and most RAG tutorials assume Python; you need fluency without becoming a Python generalist.",
        "concepts": [
            "Indentation blocks; no braces.",
            "Exceptions instead of `if err != nil` everywhere.",
            "`async`/`await` for I/O-bound LLM fan-out.",
            "venv/uv for isolated deps.",
            "List comprehensions and `with` for resource cleanup.",
        ],
        "how": "Read Python as pseudocode with types; ship services with FastAPI + Pydantic; offload CPU-heavy work to processes or Go workers.",
        "example": "Go gateway auth → Python RAG service → vector DB.",
        "bridge": "`struct`→`dataclass`/`BaseModel`; `context.Context`→`asyncio` cancellation; modules→packages.",
        "production": ["Pin deps in lockfile", "mypy/pyright on services", "Never `eval()` on LLM output"],
        "pitfalls": ["CPU loops on GIL", "Global interpreter in multi-tenant without care", "Unpinned PyPI deps"],
        "interview": ["GIL impact on embedding jobs?", "When Go vs Python?"],
        "practice": "Port one small Go handler to FastAPI with request ID middleware.",
    },
    "numpy": {
        "mental": "NumPy arrays are **typed contiguous memory** you can blast with vectorized ops—foundation for embeddings and torch tensors.",
        "why": "Read embedding code, implement similarity, debug shape errors.",
        "concepts": ["ndarray shape/dtype", "Broadcasting rules", "Vectorized ops vs Python loops", "float32 vs float64", "Views vs copies"],
        "how": "Store vectors as `(n, d)` matrices; use `@` or `np.dot` for similarity batches.",
        "example": "Normalize rows then `scores = queries @ docs.T`.",
        "bridge": "Like fixed-size byte buffers in Go—shape discipline prevents crashes.",
        "production": ["float32 for storage", "Batch queries for ANN prep"],
        "pitfalls": ["Silent broadcasting bugs", "Huge copies in loops"],
        "interview": ["Why NumPy faster than pure Python loops?"],
        "practice": "Compute top-5 cosine neighbors for 1k vectors.",
    },
    "pandas": {
        "mental": "Pandas is **SQL-like tables in memory** for eval datasets and experiment results.",
        "why": "LLM eval is rows: question, answer, label, score, model_version.",
        "concepts": ["DataFrame columns", "groupby for slice metrics", "CSV/Parquet IO", "Handling nulls", "merge for joining runs"],
        "how": "Load golden set → apply runner → aggregate precision by slice.",
        "example": "Group faithfulness by `locale` after batch eval.",
        "bridge": "Similar to SQL + Excel pivot—don't use for online serving.",
        "production": ["Version datasets in object storage", "Hash dataset id in CI"],
        "pitfalls": ["Notebook-only transforms not in pipeline", "Pandas in hot API path"],
        "interview": ["How store eval results for regression?"],
        "practice": "Build CSV with 50 rows; compute metric per `category`.",
    },
    "typing": {
        "mental": "Types are **contracts** for teams and tools—especially for LLM JSON and API schemas.",
        "why": "Catch bad tool args and response shapes before production.",
        "concepts": ["Optional, Union, list[str]", "TypedDict vs dataclass", "Protocols for duck typing", "mypy/pyright in CI", "Generics for repositories"],
        "how": "Annotate public functions; run static checker on services.",
        "example": "`def retrieve(q: str, tenant_id: UUID) -> list[Chunk]:`",
        "bridge": "Go interfaces → Protocol; structs → TypedDict/dataclass.",
        "production": ["Type tool call payloads", "Strict mypy on `services/`"],
        "pitfalls": ["`Any` everywhere", "Untyped dicts from `json.loads`"],
        "interview": ["How validate LLM JSON?"],
        "practice": "Add types to a FastAPI route and fix mypy errors.",
    },
    "async-python": {
        "mental": "`async` lets one thread **interleave waiting** on many LLM HTTP calls—like goroutines without true CPU parallelism.",
        "why": "RAG often fans out: embed, retrieve, rerank, generate—sequential sync kills latency.",
        "concepts": ["event loop", "asyncio.gather with semaphores", "httpx AsyncClient", "CPU work → ProcessPoolExecutor", "Cancellation"],
        "how": "Create client once; `await` provider calls; limit concurrency with semaphore.",
        "example": "Gather 10 retrieval queries capped at 5 concurrent.",
        "bridge": "Semaphores ≈ weighted worker pools; don't block loop with CPU.",
        "production": ["Timeouts per await", "Connection pool limits", "Graceful shutdown"],
        "pitfalls": ["Blocking IO in async route", "Unbounded gather → rate limits"],
        "interview": ["When not use async?"],
        "practice": "Async FastAPI endpoint calling two APIs in parallel.",
    },
    "pydantic": {
        "mental": "Pydantic models are **runtime-validated schemas**—ideal for API bodies and structured LLM outputs.",
        "why": "LLMs emit JSON; you need parse-or-fail, not hope.",
        "concepts": ["BaseModel fields", "Validators", "Settings from env", "JSON schema export", "model_validate_json"],
        "how": "Define response schema → parse model output → retry on validation failure.",
        "example": "Tool call args validated before SQL execution.",
        "bridge": "Like Go struct + validator tags + clearer errors.",
        "production": ["Never trust raw LLM JSON", "Log validation failures as metrics"],
        "pitfalls": ["Over-wide Optional fields", "Parsing before injection checks"],
        "interview": ["Structured output vs regex?"],
        "practice": "Pydantic model for RAG citation list; test invalid payload.",
    },
    "packaging": {
        "mental": "A Python project is **pyproject + lockfile + venv**—reproducible like `go.sum`.",
        "why": "ML images are huge; reproducible builds matter for compliance and debugging.",
        "concepts": ["uv/poetry", "extras for GPU", "src layout", "pytest in CI", "Docker multi-stage"],
        "how": "Lock deps → test → build slim runtime image with only needed wheels.",
        "example": "Separate `training` optional dep group from API image.",
        "bridge": "Monorepo: `/services/gateway-go` + `/services/rag-python`.",
        "production": ["SBOM for images", "Pin torch/CUDA base", "No secrets in images"],
        "pitfalls": ["pip install latest in prod Dockerfile", "Mixing conda and pip blindly"],
        "interview": ["How structure polyglot repo?"],
        "practice": "Add pyproject.toml with uv; run pytest in GitHub Actions.",
    },
}
