CONTENT = {
    "ai-vs-ml-vs-dl-vs-genai": {
        "mental": "Picture nested scopes: **AI** is the goal (machines doing tasks that look intelligent). **ML** learns patterns from data. **DL** uses deep neural networks. **GenAI** generates new content (text, code, images) from learned distributions—what most LLM products are.",
        "why": "Teams use the wrong tool when labels are fuzzy—e.g. an LLM where XGBoost would be cheaper and auditable. You need vocabulary to place components in architecture reviews.",
        "concepts": [
            "Discriminative models predict labels; generative models model P(x) or P(x|y).",
            "LLM apps are mostly integration: retrieval, tools, eval—not training foundation models.",
            "Classical ML still wins on structured tabular fraud, churn, ranking with features.",
            "GenAI outputs are stochastic; SLIs must include quality, not only HTTP 200.",
            "Transfer learning: pretrain once, adapt many products via prompts/RAG/LoRA.",
        ],
        "how": "Data flows through feature extraction (hand-built or learned), a model produces scores or token distributions, and a serving layer applies policy. GenAI adds long contexts, tools, and safety filters.",
        "example": "Fraud: gradient-boosted trees on transaction features. Internal copilot: RAG over Confluence + GPT-4 class API + gateway quotas.",
        "bridge": "Treat an LLM endpoint like an unreliable downstream microservice: timeouts, circuit breakers, idempotency, and observability you already use in Go services.",
        "production": [
            "Version models, prompts, and indexes separately in change management.",
            "Define SLOs on latency and quality (eval), not only availability.",
            "Keep PII out of training logs; redact in traces.",
        ],
        "pitfalls": [
            "Calling everything 'AI' without measurable task metrics.",
            "Replacing calibrated models with LLMs for numeric prediction.",
            "Ignoring cost per successful task.",
        ],
        "interview": [
            "When would you not use an LLM?",
            "Difference between RAG and fine-tuning in one sentence each?",
            "How does GenAI change monitoring vs a REST CRUD API?",
        ],
        "practice": "List five features at your job; classify each as Rules / ML / LLM / Hybrid and justify latency and risk.",
    },
    "probability-statistics-for-ai": {
        "mental": "LLM outputs are **samples** from a distribution. Evaluation is **estimation** from finite data—confidence intervals matter as much as point scores.",
        "why": "You will gate releases on eval metrics; misunderstanding variance causes false 'wins' and production regressions.",
        "concepts": [
            "Random variables, expectation, variance.",
            "Precision, recall, F1—especially under class imbalance.",
            "Bayes: prior + likelihood → posterior (intuition for spam, retrieval priors).",
            "Train/val/test leakage destroys offline metrics.",
            "Bootstrap CIs for faithfulness or win-rate between prompts.",
        ],
        "how": "Collect labeled or LLM-judged outcomes, aggregate metrics, compare with statistical discipline, slice by tenant/locale/query length.",
        "example": "RAG faithfulness 82% on 200 questions—report CI before shipping prompt v2.",
        "bridge": "Same mindset as SRE error budgets: sample noise vs real incident.",
        "production": ["Stratified eval sets", "Holdout untouched during iteration", "Track n per slice"],
        "pitfalls": ["Optimizing on test set", "Single-number accuracy on rare events", "Ignoring multiple comparisons across prompts"],
        "interview": ["Precision vs recall trade-off example?", "Why point estimate on 50 examples is weak?"],
        "practice": "Bootstrap CI for a binary metric on your own 100-row eval CSV.",
    },
    "linear-algebra-for-ai": {
        "mental": "Embeddings are **vectors**. Transformers are **stacked matrix multiplies** plus attention mixing. Shape errors are the #1 notebook bug.",
        "why": "You debug retrieval (cosine), serving memory (tensor shapes), and read papers/engine blogs without getting lost.",
        "concepts": [
            "Dot product ↔ cosine when vectors are normalized.",
            "Matrices as linear maps; MLP layers in transformers.",
            "Attention as weighted sum of value vectors.",
            "Batch × seq × hidden layout on GPU.",
            "Rank/intuition for PCA and compression.",
        ],
        "how": "Token IDs → embedding lookup → layers apply W matrices → logits vector over vocabulary.",
        "example": "Query embedding near 'refund policy' chunks, far from 'weather' chunks in cosine space.",
        "bridge": "Like sizing Kafka messages vs consumer batch—dimension and batch drive memory.",
        "production": ["Pick embedding dim vs storage cost", "Normalize vectors for cosine ANN", "Watch dtype FP16/BF16"],
        "pitfalls": ["L2 vs cosine confusion", "Wrong pooling (mean vs last token)", "Assuming Euclidean on unnormalized vectors"],
        "interview": ["Attention equation?", "Why cosine for embeddings?"],
        "practice": "Implement cosine similarity in Go on []float32.",
    },
    "optimization": {
        "mental": "Training **walks downhill** on loss; inference **freezes** weights and optimizes latency/cost instead.",
        "why": "Fine-tune decisions, learning rate disasters, and 'why GPU hours exploded' all tie to optimization.",
        "concepts": [
            "Loss (cross-entropy for tokens), gradients, SGD/Adam.",
            "Overfitting vs underfitting; early stopping.",
            "LoRA: optimize low-rank adapters, not full weights.",
            "Regularization: weight decay, dropout (training only).",
            "Learning rate warmup and schedules at scale.",
        ],
        "how": "Forward → loss → backward → optimizer step; repeat until validation metric plateaus.",
        "example": "LoRA on 7B for JSON ticket classification—monitor val F1, stop when flat.",
        "bridge": "Like tuning JVM heap vs throughput—different phase, different objective.",
        "production": ["Checkpoint to object storage", "Pin data + seed for reproducibility", "Separate train and infer images"],
        "pitfalls": ["NaN loss (LR too high)", "Catastrophic forgetting on small FT sets", "Evaluating train split"],
        "interview": ["Training vs inference optimization goals?", "What is LoRA optimizing?"],
        "practice": "Sketch loss curve and mark early-stop point; tie to business metric.",
    },
    "information-theory": {
        "mental": "Cross-entropy measures **surprise** when the model predicts the next token. Low surprise = model assigns high probability to true tokens.",
        "why": "Connects training loss, perplexity, tokenization trade-offs, and why long outputs cost money.",
        "concepts": [
            "Entropy: uncertainty in bits.",
            "Cross-entropy and KL divergence (intuition).",
            "Perplexity as effective branching factor.",
            "Tokenization compresses text into variable-length codes.",
            "Quantization discards information for speed.",
        ],
        "how": "Model outputs logits → softmax → compare to true token via -log p.",
        "example": "Perplexity drop after instruction tuning means model is 'less surprised' by chat formatting.",
        "bridge": "Billing is per token—codec choice is a cost architecture decision.",
        "production": ["Logprobs for anomaly detection (careful PII)", "Context stuffing increases billed entropy carriers"],
        "pitfalls": ["Chasing perplexity alone for product quality", "Ignoring tokenizer differences across models"],
        "interview": ["Perplexity in plain English?", "Why more tokens can mean higher bill without better answers?"],
        "practice": "Compare chars/token for English vs JSON-heavy prompts.",
    },
    "mental-models": {
        "mental": "A **catalog of pictures** for the AI stack: token, embedding, RAG, agent, gateway, KV cache, etc. Reason about unfamiliar systems by slotting components.",
        "why": "Interview and incident response need fast mental simulation, not API memorization.",
        "concepts": [
            "Token = billing + context unit.",
            "RAG = open-book exam with a librarian (retriever).",
            "Agent = intern with a phone (tools) and a manager (your code).",
            "Gateway = air traffic control for models.",
            "Inference = prefill (read prompt) + decode (stamp tokens).",
        ],
        "how": "Map each request path: data → retrieval → prompt → model → tools → observability.",
        "example": "Incident: latency up—is it retrieval, prefill, or provider throttle?",
        "bridge": "Same as tracing a request through API gateway → service mesh → DB.",
        "production": ["Draw one diagram per system you own", "Label failure points before launch"],
        "pitfalls": ["Treating LLM as deterministic function", "Skipping retrieval in RAG debug"],
        "interview": ["Explain KV cache in 30 seconds.", "RAG vs fine-tune?"],
        "practice": "Redraw the stack from memory; compare to README diagram.",
        "extra": "This file is the index—deep dives live in module topics.",
    },
}
